myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlinecourse/', include('onlinecourse.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'onlinecourse'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL
    path(route='', view=views.CourseListView.as_view(), name='index'),
    path('homework/', view=views.HomeworkView.as_view(), name='homework'),
    path('homework/<int:pk>/', views.HomeworkDetailView.as_view(), name='homework_details'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    # ex: /onlinecourse/5/
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    # ex: /enroll/5/
    path('<int:course_id>/enroll/', views.enroll, name='enroll'),
    path('<int:homework_id>/check/', views.check, name='check'),
    #path('show/', views.show, name='show'),
    path('<int:course_id>/submit/', views.submit, name='submit'),
    path('course/<int:course_id>/submission/<int:submission_id>/result/', views.show_exam_result, name='result'),
    # <HINT> Create a route for submit view
    path('<int:homework_id>/submithomework/', views.submithomework, name='submithomework'),
    #path('homework/<int:homework_id>/homeworkanswer/<int:homeworkanswer_id>/result/', views.show_homework_result,name='homeworkresult'),
    # <HINT> Create a route for show_exam_result view

 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/models.py
import sys
from django.utils.timezone import now
try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()
    phone_num = models.CharField(
        null=False,
        max_length=20
    )
    university = models.CharField(
        null=False,
        max_length=20
    )
    college = models.CharField(
        null=False,
        default="",
        max_length=20
    )

    school_num = models.CharField(
        null=False,
        max_length=20
    )


    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    phone_num = models.CharField(
        null=False,
        max_length=20
    )
    university = models.CharField(
        null=False,
        max_length=20
    )
    college = models.CharField(
        null=False,
        default="",
        max_length=20
    )
    major = models.CharField(
        null=False,
        max_length=20
    )
    class_num = models.CharField(
        null=False,
        max_length=20
    )
    school_num = models.CharField(
        null=False,
        max_length=20
    )

    def __str__(self):
        return self.user.username + "," + \
               self.occupation


# Course model
class Course(models.Model):
    name = models.CharField(null=False, max_length=30, default='新建课程')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


# Lesson model
class Lesson(models.Model):
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Enrollment model
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)
    testgrade = models.CharField(
        null=False,
        max_length=20
    )


class Homework(models.Model):
    name = models.CharField(
        null=False,
        max_length=20
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default="1", on_delete=models.CASCADE)

    course = models.ForeignKey(to="course", on_delete=models.CASCADE, default=1)
    deadline = models.DateField(default=now)
    grade = models.CharField(
        null=False,
        default= '0',
        max_length=20
    )


# <HINT> Create a Question Model with:
class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)# Foreign key to lesson
    text = models.TextField()# question text
    grade = models.IntegerField(default=5)# question grade/mark
    homework= models.ForeignKey(Homework,blank = True, on_delete=models.CASCADE)

    # <HINT> A sample model method to calculate if learner get the score of the question
    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
        if all_answers == selected_correct:
            return True
        else:
            return False


#  <HINT> Create a Choice Model with:
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()
    is_correct = models.BooleanField()

# <HINT> The submission model
class Submission(models.Model):
   enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
   choices = models.ManyToManyField(Choice)


class Homeworkanswer(models.Model):
   homework = models.ForeignKey(Homework, on_delete=models.CASCADE)
   choices = models.ManyToManyField(Choice)

onlinecourse/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# <HINT> Import any new Models here
from .models import Course, Enrollment, Homework, Question, Choice, Submission, Homeworkanswer
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'onlinecourse/user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("onlinecourse:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'onlinecourse/user_registration_bootstrap.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('onlinecourse:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'onlinecourse/user_login_bootstrap.html', context)
    else:
        return render(request, 'onlinecourse/user_login_bootstrap.html', context)


def logout_request(request):
    logout(request)
    return redirect('onlinecourse:index')


def check_if_enrolled(user, course):
    is_enrolled = False
    if user.id is not None:
        # Check if user enrolled
        num_results = Enrollment.objects.filter(user=user, course=course).count()
        if num_results > 0:
            is_enrolled = True
    return is_enrolled


# CourseListView
class CourseListView(generic.ListView):
    template_name = 'onlinecourse/course_list_bootstrap.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user = self.request.user
        courses = Course.objects.order_by('-total_enrollment')[:10]
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = check_if_enrolled(user, course)
        return courses


class HomeworkView(generic.ListView):
    model = Homework
    template_name = 'onlinecourse/homework_bootstrap.html'
    queryset = Homework.objects.all()


class HomeworkDetailView(generic.DetailView):
    model = Homework
    template_name = 'onlinecourse/homework_detail_bootstrap.html'


class CourseDetailView(generic.DetailView):
    model = Course
    template_name = 'onlinecourse/course_detail_bootstrap.html'


def enroll(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user

    is_enrolled = check_if_enrolled(user, course)
    if not is_enrolled and user.is_authenticated:
        # Create an enrollment
        Enrollment.objects.create(user=user, course=course, mode='honor')
        course.total_enrollment += 1
        course.save()

    return HttpResponseRedirect(reverse(viewname='onlinecourse:course_details', args=(course.id,)))


def check(request, homework_id):
    homework = get_object_or_404(Homework, pk=homework_id)
    user = request.user
    context={
        "user":user,
        "homework_id":homework_id
    }
    #is_checked = check_if_checked(user, homework_id)
    print(homework.id)
    #if is_checked and user.is_authenticated:
    return HttpResponseRedirect(reverse(viewname='onlinecourse:homework_details', args=(homework.id,)))


# <HINT> Create a submit view to create an exam submission record for a course enrollment,
# you may implement it based on following logic:
# Get user and course object, then get the associated enrollment object created when the user enrolled the course
# Create a submission object referring to the enrollment
# Collect the selected choices from exam form
# Add each selected choice object to the submission object
# Redirect to show_exam_result with the submission id
def submit(request, course_id):
    user = request.user
    course = get_object_or_404(Course, pk=course_id)
    enrollment = Enrollment.objects.get(user=user, course=course)
    submission = Submission.objects.create(enrollment=enrollment)
    submitted_anwsers = extract_answers(request)
    submission.choices.add(*submitted_anwsers)
    submission_id = submission.id
    return HttpResponseRedirect(reverse(viewname='onlinecourse:result', args=(course_id, submission_id,)))



def submithomework(request, homework_id):
    homework = get_object_or_404(Homework, pk=homework_id)

    homeworkanswer = Homeworkanswer.objects.create(homework=homework)
    submitted_anwsers = extract_answers(request)
    homeworkanswer.choices.add(*submitted_anwsers)
    print(homework_id)


    context = {}

    choice_ids = homeworkanswer.choices.all()
    score = 0
    totalnum = 0
    rightnum = 0
    for question in homework.question_set.all():
        totalnum += 1
        if question.is_get_score(choice_ids):
            #score = score + question.grade
            rightnum += 1
    score = (rightnum / totalnum)*100
    print(score)
    context['homework'] = homework
    context['selected_ids'] = choice_ids
    context['grade'] = score
    user = request.user
    print(user.id)
    #Homework = get_object_or_404(Homework, pk=homework_id)
    Homework.objects.filter(user_id=user.id).update(grade=score)
    homework.save()
    return render(request, 'onlinecourse/homework_result_bootstrap.html', context)
    # 将指定条件的数据更新，均支持 **kwargs


# <HINT> A example method to collect the selected choices from the exam form from the request object
def extract_answers(request):
    submitted_anwsers = []
    for key in request.POST:
        if key.startswith('choice'):
            value = request.POST[key]
            choice_id = int(value)
            submitted_anwsers.append(choice_id)
    return submitted_anwsers


# <HINT> Create an exam result view to check if learner passed exam and show their question results and result for each question,
# you may implement it based on the following logic:
# Get course and submission based on their ids
# Get the selected choice ids from the submission record
# For each selected choice, check if it is a correct answer or not
# Calculate the total score
def show_exam_result(request, course_id, submission_id):
    context = {}
    course = get_object_or_404(Course, pk=course_id)
    submission = get_object_or_404(Submission, pk=submission_id)
    choice_ids = submission.choices.all()
    score = 0
    totalnum = 0
    rightnum = 0
    for question in course.question_set.all():
        totalnum += 1
        if question.is_get_score(choice_ids):
            #score = score + question.grade
            rightnum += 1
    score = (rightnum / totalnum)*100
    print(score)
    context['course'] = course
    context['selected_ids'] = choice_ids
    context['grade'] = score
    user = request.user
    print(user)
    Enrollment.objects.update(user=user,  testgrade=score)

    course.save()
    return render(request, 'onlinecourse/exam_result_bootstrap.html', context)

#def show_homework_result(request, homework_id, homeworkanswer_id):


def test(request):
    username = request.POST.get("username")
    print(username)
    context = {
        "username":username
    }
    return render(request,"test.html",context=context)

onlinecourse/templates/onlinecourse/course_detail_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid">
            <h2>{{ username }}</h2>
            <div class="card-columns-vertical">
                {% for lesson in course.lesson_set.all %}
                    <div class="card mt-1">
                        <div class="card-header"><h5>Lesson {{lesson.order|add:1}}: {{lesson.title}}</h5></div>
                        <div class="card-body">{{lesson.content}}</div>
                    </div>
                {% endfor %}
            </div>
            <!-- Task: show questions and choices -->
            <!-- <HINT> Use Bootstrap Collapse to hide exam first, more details could be found here
            https://www.w3schools.com/bootstrap4/bootstrap_collapse.asp-->

            

            <!-- A collapse example here: -->
            <button data-target="#exam">Exam</button>
            <div id="exam" class="collapse">
                {% if user.is_authenticated %}
                    <form id="questionform" action={% url 'onlinecourse:submit' course.id %} method="post">
                        {% for question in course.question_set.all %}
                            <div class="card mt-1">
                                <div class="card-header"><h5>{{ question.text }}</h5></div>
                                {% csrf_token %}
                                <div class="form-group">
                                {% for choice in question.choice_set.all %}
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="choice_{{choice.id}}"
                                                class="form-check-input" id="{{choice.id}}"
                                                value="{{choice.id}}">{{ choice.text }}
                                                
                                        </label>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <input class="btn btn-success btn-block" type="submit" value="Submit">
                    </form>
                {% endif %}
            </div>
                <!-- Click to expand elements within the collapse div -->
            

           

            <!-- <HINT> If user is authenticated, show course exam with a list of question -->

            <!-- <HINT> Each example will have many questions -->

            <!-- <HINT> Each question will have many choices -->


            <!-- <HINT> Create a form to collect the selected choices for all questions -->
            <!-- <HINT> For each question choice, you may create a checkbox input like
            <input type="check" name="choice_{{choice.id}}" id="{{choice.id}}" ...>
            -->

            <!-- A choice submission form example
            <form id="questionform" action="point to a submit view" method="post">
                        ... for each question in the course ...
                        <div class="card mt-1">
                            <div class="card-header"><h5>{{ question.question_text}}</h5></div>
                            {% csrf_token %}
                            <div class="form-group">
                               ... for each choice in the question ...
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="choice_{{choice.id}}"
                                               class="form-check-input" id="{{choice.id}}"
                                               value="{{choice.id}}">{{ choice.choice_text }}
                                    </label>
                                </div>
                            </div>
                        </div>
                    <input class="btn btn-success btn-block" type="submit" value="Submit">
            </form> -->

            <!--Check here to see more details Bootstrap checkbox
             https://www.w3schools.com/bootstrap4/bootstrap_forms_inputs.asp-->
    </div>
</body>
</html>

onlinecourse/templates/onlinecourse/course_list_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>
<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="#">学习通</a>
                  <a class="navbar-brand" href="{% url 'onlinecourse:homework' %}">作业</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    {% if course_list %}
        <div class="container">
        
            <div class="card-deck">
                {% for course in course_list %}
                <div class="col-md-4">
                         <div class="card" style="width: 36rem;">
                          <img class="card-img-left" src="{{MEDIA_URL}}/{{ course.image }}" width="240px" height="240px"
                               alt="Course image">
                          <div class="card-body bg-light">
                              <h5 class="card-title">{{ course.name }}, <span class="text-success">
                                  {{ course.total_enrollment}} enrolled</span></h5>
                            <p class="card-text">{{ course.description}}</p>
                            <form action="{% url 'onlinecourse:enroll' course.id %}" method="post">
                                  {% csrf_token %}
                                  <input class="btn btn-primary"  type="submit"
                                         value="{% if course.is_enrolled %}Enter{% else %}Enroll{% endif %} ">
                            </form>
                          </div>
                        </div>
                </div>
                {% endfor %}
            
            </div>
        </div>
    {% else %}
        <p>No courses are available.</p>
    {% endif %}
</body>
</html>

onlinecourse/templates/onlinecourse/homework_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid">


    {% for homework in homework_list %}
    {% ifequal homework.user_id user.id %}
    <br>
    <form action="{% url 'onlinecourse:check' homework.id %}" method="post">
        {% csrf_token %}
        <input class="btn btn-primary"  type="submit"
        value="{{ homework.name }}">
        <br>
    </form>
    {% endifequal %}
    {% endfor %}
    </div>
</body>
</html>

onlinecourse/templates/onlinecourse/homework_detail_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid">
          
    <h2>{{homework.name}}</h2>
                {% if user.is_authenticated %}
                    <form id="questionform"  action={% url 'onlinecourse:submithomework' homework.id %} method="post">
                        {% for question in homework.question_set.all %}
                            <div class="card mt-1">
                                <div class="card-header"><h5>{{ question.text }}</h5></div>
                                {% csrf_token %}
                                <div class="form-group">
                                {% for choice in question.choice_set.all %}
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="checkbox" name="choice_{{choice.id}}"
                                                class="form-check-input" id="{{choice.id}}"
                                                value="{{choice.id}}">{{ choice.text }}
                                        </label>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                        <input class="btn btn-success btn-block" type="submit" value="Submit">
                    </form>
                {% endif %}



    </div>
</body>
</html>

onlinecourse/templates/onlinecourse/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>1
<form action="onlinecourse/test" method="post">
    <input type="text" name="username" value="2"/>
    <input type="submit" value="替吉奥">

</form>
{{ username }}
</body>
</html>